### ISSUE TITLE
Move logs from cubejs-server-core to cubejs-server

### ISSUE THREAD

**Issue by dtslvr** [statsbotco/cube.js#23]
Hi all,

As we are using _Cubejs_ in an [embedded environment](https://github.com/statsbotco/cube.js#cubejsservercorecreateoptions) with our own _Express_ server, the following logs are not correct anymore and a bit misleading:

* ```console.log(`🔒 Your temporary cube.js token: ${cubejsToken}`);``` ([Link](https://github.com/statsbotco/cube.js/blob/1525ed508982a85c7bbc42732f77fbb28bcf66aa/packages/cubejs-server-core/core/index.js#L174))
* ```console.log(`🦅 Dev environment available at ${localUrl}`);``` ([Link](https://github.com/statsbotco/cube.js/blob/1525ed508982a85c7bbc42732f77fbb28bcf66aa/packages/cubejs-server-core/core/index.js#L175))

Suggestion: These logs should not reside in `cubejs-server-core`, but in `cubejs-server`.

**Comment by paveltiunov** [comment]
@dtslvr Thanks for posting this Thomas! 

It's an interesting scenario. Actually this code was moved from `cubejs-server`. The reason is `server-core` is reused also in `cubejs-serverless` package. This code is a part of dev server which is required for serverless deployment as well.

Could you please elaborate a little bit on your use case? Do you want just to disable dev server completely? If `NODE_ENV` is set to `production` it'll be disabled -- it's how it intended to run in production environments.

**Comment by dtslvr** [comment]
We are only importing `cubejs-server-core` as a part of our `Express` server. We implemented something similar to `cubejs-server` by ourselves as the entry point.

So `🦅 Dev environment available at http://localhost:4000` is wrong in our scenario, we're using a different port and `🔒 Your temporary cube.js token: ey...` should not be logged at all.

I know it's only in development environment, so it's not critical :blush:

**Comment by paveltiunov** [comment]
Would it solve your issue if we'll introduce a `devServer` option for `CubejsServerCore.create()` which will take precedence over `NODE_ENV`?

**Comment by dtslvr** [comment]
Yes, adding `devServer: boolean` to `options` would be fine.

**Comment by paveltiunov** [comment]
Let's do it then! Thomas would love if you can provide PR for that.

**Comment by dtslvr** [comment]
I have created a pull request: https://github.com/statsbotco/cube.js/pull/29
